wireplumber.properties = {
    session.suspend-timeout-seconds = 0
}

monitor.alsa.rules = [
    {
        matches = [ { node.name = "~alsa_output.*" } ]
        actions = {
            update-props = {
                api.alsa.period-size            = 1024
                api.alsa.period-num             = 2
                api.alsa.headroom               = 0
                audio.rate                      = 48000
                audio.allowed-rates             = [ 48000 ]
                audio.channels                  = 2
                audio.position                  = [ FL FR ]
                node.pause-on-idle              = false
                session.suspend-timeout-seconds = 0
            }
        }
    },
    {
        matches = [ { node.name = "~alsa_input.*" } ]
        actions = {
            update-props = {
                api.alsa.period-size            = 1024
                api.alsa.period-num             = 2
                api.alsa.headroom               = 0
                audio.rate                      = 48000
                node.pause-on-idle              = false
                session.suspend-timeout-seconds = 0
            }
        }
    }
]
