general { 
    gaps_in = 2
    gaps_out = 0
    # col.active_border = rgba(484848BB)
    # col.inactive_border = rgba(44444455)

}

windowrule = border_size 0, match:float 0
windowrule = rounding 0, match:float 0
windowrule = no_shadow on, match:float 0
windowrule = rounding 0, match:float 0, match:class steam

# vim: set ft=hyprlang :
